# creation of objects

In [5]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()

test()for the class and method


In [7]:
def test():
    print("test() for the function")
    return
test()

test() for the function


In [13]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(6)

720

In [17]:
def fact(n):
    if(n==1):
        return 1
    else:
        return n*fact(n-1)
fact(6)

720

In [31]:
class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1=",self.p1)
        print("p2=",self.p2)
c1=demo2()
c1.accept(10,20)
c1.display()

p1= 10
p2= 20


In [32]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(10,20))

30


In [ ]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemploye(self):
        return false
class employe(person)
    

# python numpy

In [38]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [34]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [36]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
array+10
print(array)

[1 2 3 4]


In [37]:
 import numpy as np
array=np.array(list)
print(array.shape)
print(array.dtype)


(4,)
int32


In [39]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [40]:
#reshaping the given array
#numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
 a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [44]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [45]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.59661473 5.3183605  3.73311862 5.40887386 5.52181643 5.56558009
 5.1878668  4.54724141 4.79329722 4.42328059]


In [50]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [62]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [61]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [63]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=14
np.asarray(a)[3][3]=16
print(a)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [65]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(1,100,9)
#1 to 100 between 9 diff

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [68]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [69]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [72]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row",a1[:,1])

slicing row [2 5]


In [74]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last col:",a1[:,2])

slicing last col: [3 6]


In [86]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row andf col:",a1[1,:1])

slicing row andf col: [4]


In [85]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [78]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row",a1[1])

second row [4 5 6]


In [87]:
a1=np.random.normal(5,1,10)
print(a1)

[5.1250833  4.55769325 4.01106587 3.51361071 4.42502398 6.77167129
 3.81871267 4.35470239 5.37475683 6.67679669]


In [88]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value",np.min(a1))
print("max value",np.max(a1))
print("mean value",np.mean(a1))
print("median value",np.median(a1))


[3.88549512 5.10245684 4.87171492 3.87186746 6.03956934 4.16644475
 6.30947402 3.83116538 4.2340323  4.6302104 ]
min value 3.831165379288586
max value 6.309474024673099
mean value 4.694243052383491
median value 4.43212134642447


In [89]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [91]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [92]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [94]:
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


In [ ]:
knjkhjyo kj[j kojjkuo ojtojiu]hygoijuh jgohjity0j jkghngpji kjohijh khi mdc1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)hkijhogpighj lnmkfpgtoji ;dsiog dpro5it 
eoipm, ]rt'; 
ihjfdy og